#! /bin/sh

bspc config border_width        1
bspc config window_gap         5
bspc config top_padding        26
bspc config left_padding       0
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a Steam desktop=^3 follow=on
bspc rule -a Gimp desktop=^5 follow=on
bspc rule -a qutebrowser desktop=^2
bspc rule -a mutt desktop=^5
bspc rule -a ranger desktop=^4

## autostart
#unclutter -root -idle 1 &
feh --bg-scale /home/akshaysth/Pictures/wallhaven-25150.jpg &
#feh --bg-scale /home/akshaysth/Pictures/sea_coast_excitement_cloudy_clouds_bad_weather_foam_52140_2560x1600.jpg &
compton --vsync opengl-swc --shadow-exclude 'n:a:Conky' -b &
redshift &
# conky &
/opt/dropbox/dropboxd &
mpd &
cd /home/akshaysth/.config/bspwm/panel/ && ./panel &
